# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gregory Cowley - Designer/Developer
author: Gregory Cowley
email: gregory@cowleyxd.com
description: >- # this means to ignore newlines until "baseurl:"
  With over 25 years of professional interactive design and development 
  experience, I offer a strong understanding of and intuitive sense for 
  user interface design. I combine problem-solving with creativity and 
  communication, and I have a keen sense of attention to detail. I have 
  studied the business from many different angles and learned about the 
  many different sides of an industry that connects customers 
  with products.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cowley.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  gregorycowley
linkedin_username: gregorycowley

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
