<?php

class PeThemeConstantData {
	public $yesno;
	public $delay;
	public $icons;
	public $fields;

	public function __construct() {
		$this->yesno = 
			array(
				  __pe("Yes")=>"yes",
				  __pe("No")=>"no"
				  );
		
		$this->delay = 
			array(
				  __pe("Don't Auto Rotate Slides")=>0,
				  "2" => 2,
				  "3" => 3,
				  "4" => 4,
				  "5" => 5,
				  "6" => 6,
				  "7" => 7,
				  "8" => 8,
				  "9" => 9,
				  "10" => 10,
				  "15" => 15,
				  "20" => 20,
				  "25" => 25,
				  "30" => 30
				  );

		$this->icons = 
			array(
				  "icon-adjust",
				  "icon-align-center",
				  "icon-align-justify",
				  "icon-align-left",
				  "icon-align-right",
				  "icon-arrow-down",
				  "icon-arrow-left",
				  "icon-arrow-right",
				  "icon-arrow-up",
				  "icon-asterisk",
				  "icon-backward",
				  "icon-ban-circle",
				  "icon-barcode",
				  "icon-bell",
				  "icon-bold",
				  "icon-book",
				  "icon-bookmark",
				  "icon-briefcase",
				  "icon-bullhorn",
				  "icon-calendar",
				  "icon-camera",
				  "icon-certificate",
				  "icon-check",
				  "icon-chevron-down",
				  "icon-chevron-left",
				  "icon-chevron-right",
				  "icon-chevron-up",
				  "icon-circle-arrow-down",
				  "icon-circle-arrow-left",
				  "icon-circle-arrow-right",
				  "icon-circle-arrow-up",
				  "icon-cog",
				  "icon-comment",
				  "icon-download",
				  "icon-download-alt",
				  "icon-edit",
				  "icon-eject",
				  "icon-envelope",
				  "icon-exclamation-sign",
				  "icon-eye-close",
				  "icon-eye-open",
				  "icon-facetime-video",
				  "icon-fast-backward",
				  "icon-fast-forward",
				  "icon-file",
				  "icon-film",
				  "icon-filter",
				  "icon-fire",
				  "icon-flag",
				  "icon-folder-close",
				  "icon-folder-open",
				  "icon-font",
				  "icon-forward",
				  "icon-fullscreen",
				  "icon-gift",
				  "icon-glass",
				  "icon-globe",
				  "icon-hand-down",
				  "icon-hand-left",
				  "icon-hand-right",
				  "icon-hand-up",
				  "icon-hdd",
				  "icon-headphones",
				  "icon-heart",
				  "icon-home",
				  "icon-inbox",
				  "icon-indent-left",
				  "icon-indent-right",
				  "icon-info-sign",
				  "icon-italic",
				  "icon-leaf",
				  "icon-list",
				  "icon-list-alt",
				  "icon-lock",
				  "icon-magnet",
				  "icon-map-marker",
				  "icon-minus",
				  "icon-minus-sign",
				  "icon-move",
				  "icon-music",
				  "icon-off",
				  "icon-ok",
				  "icon-ok-circle",
				  "icon-ok-sign",
				  "icon-pause",
				  "icon-pencil",
				  "icon-picture",
				  "icon-plane",
				  "icon-play",
				  "icon-play-circle",
				  "icon-plus",
				  "icon-plus-sign",
				  "icon-print",
				  "icon-qrcode",
				  "icon-question-sign",
				  "icon-random",
				  "icon-refresh",
				  "icon-remove",
				  "icon-remove-circle",
				  "icon-remove-sign",
				  "icon-repeat",
				  "icon-resize-full",
				  "icon-resize-horizontal",
				  "icon-resize-small",
				  "icon-resize-vertical",
				  "icon-retweet",
				  "icon-road",
				  "icon-screenshot",
				  "icon-search",
				  "icon-share",
				  "icon-share-alt",
				  "icon-shopping-cart",
				  "icon-signal",
				  "icon-star",
				  "icon-star-empty",
				  "icon-step-backward",
				  "icon-step-forward",
				  "icon-stop",
				  "icon-tag",
				  "icon-tags",
				  "icon-tasks",
				  "icon-text-height",
				  "icon-text-width",
				  "icon-th",
				  "icon-th-large",
				  "icon-th-list",
				  "icon-thumbs-down",
				  "icon-thumbs-up",
				  "icon-time",
				  "icon-tint",
				  "icon-trash",
				  "icon-upload",
				  "icon-user",
				  "icon-volume-down",
				  "icon-volume-off",
				  "icon-volume-up",
				  "icon-warning-sign",
				  "icon-wrench",
				  "icon-zoom-in",
				  "icon-zoom-out"
				  );
			

		$this->fields = new StdClass();

		$this->fields->icon =
			array(
				  "label" => __pe("Icon Type"),
				  "type" => "Select",
				  "description" => __pe("Select the desired icon type. See the help documentation for a link to view the available icons"),
				  "single" => true,
				  "options" => $this->icons,
				  "default" => "icon-file"
				  );
	}
	
}

?>